### ISSUE TITLE
Compilation problem on Mint 20

### ISSUE THREAD

**Issue by DanielWielanek** [FairRootGroup/UniGen#10]
Hi,
I cannot compile Unigen on my system (I use ROOT from FairSoft)
I get errors like:
_make[1]: Entering '/home/daniel/Cpp/Makra/UnigenC/trunk/base'
make[1]: *** No rule to make 'UniGenDict.h', required by 'UniGenDict.o'. Stop._
I noticed that UniGenDict.h is not created (but UniGenDict.cxx is)
It seems that replacing:
`$(TARGET)Dict.o : $(TARGET)Dict.cxx $(TARGET)Dict.h`
by
`$(TARGET)Dict.o : $(TARGET)Dict.cxx `
in line 46 of config/MakeLib solves the issue

**Comment by kresan** [comment]
Can it be that you are using outdated version, from subversion repo or so?

This is line 49 in `config/Makelib`:

```
$(TARGET)Dict.o : $(TARGET)Dict.cxx
```

**Comment by DanielWielanek** [comment]
Yes, I have some very old version. Sorry. I will close the issue.
