### ISSUE TITLE
Installing Uigen v2.3 on ROOT Version: 6.30/02 Built for linuxx8664gcc on Jan 04 2024, 10:37:51 From tags/v6-30-02@

### ISSUE THREAD

**Issue by arshedmasoodi** [FairRootGroup/UniGen#11]
hi
ROOT Version: 6.30/02
Built for linuxx8664gcc on Jan 04 2024, 10:37:51
From tags/v6-30-02@

was trying to install Unigen v2.3 on the above system and i get the following error
make UniGen_Install install
make: Nothing to be done for 'UniGen_Install'.
make[1]: Entering directory '/home/arshad/WorkSpace/LEARN/UniGen/base'
Compiling src/UEvent.cxx ...
Compiling src/UManager.cxx ...
Compiling src/UParticle.cxx ...
Compiling src/UPIDConverter.cxx ...
Compiling src/URun.cxx ...
Compiling src/UTask.cxx ...
Generating dictionary UniGenDict.cxx ...
In file included from input_line_9:3:
./include/UEvent.h:40:17: error: field has incomplete type 'TString'
  TString       fComment;      // Generator-specific information
                ^
/home/arshad/WorkSpace/RootInstallations/root_install/include/Rtypes.h:55:7: note: forward declaration of 'TString'
class TString;
      ^
Error: rootcint: compilation failure (./UniGenDict34651f2458_dictUmbrella.h)
make[1]: *** [/home/arshad/WorkSpace/LEARN/UniGen/config/Makelib:23: UniGenDict.cxx] Error 1
make[1]: Leaving directory '/home/arshad/WorkSpace/LEARN/UniGen/base'
make[1]: Entering directory '/home/arshad/WorkSpace/LEARN/UniGen/converters'
Compiling ampt2u.cpp ...
Building /home/arshad/WorkSpace/LEARN/UniGen/bin/ampt2u ...
/usr/bin/ld: cannot find -lUniGen: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [/home/arshad/WorkSpace/LEARN/UniGen/config/Makebin:25: /home/arshad/WorkSpace/LEARN/UniGen/bin/ampt2u] Error 1
make[1]: Leaving directory '/home/arshad/WorkSpace/LEARN/UniGen/converters'
make[1]: Entering directory '/home/arshad/WorkSpace/LEARN/UniGen/input'
Installing data files for converters...
mkdir -p -m 0755 /home/arshad/WorkSpace/LEARN/UniGen/input
install -m 0644 pluto_pdg.dat urqmd_pdg.dat werner_pdg.dat /home/arshad/WorkSpace/LEARN/UniGen/input
install: 'pluto_pdg.dat' and '/home/arshad/WorkSpace/LEARN/UniGen/input/pluto_pdg.dat' are the same file
install: 'urqmd_pdg.dat' and '/home/arshad/WorkSpace/LEARN/UniGen/input/urqmd_pdg.dat' are the same file
install: 'werner_pdg.dat' and '/home/arshad/WorkSpace/LEARN/UniGen/input/werner_pdg.dat' are the same file
make[1]: *** [Makefile:10: install] Error 1
make[1]: Leaving directory '/home/arshad/WorkSpace/LEARN/UniGen/input'
make[1]: Entering directory '/home/arshad/WorkSpace/LEARN/UniGen/tasks'
Compiling src/UTaskCm2Lab.cxx ...
Compiling src/UTaskFilter.cxx ...
Compiling src/UTaskGetInelastic.cxx ...
Compiling src/UTaskKin.cxx ...
Compiling src/UTaskLab2Cm.cxx ...
Compiling src/UTaskRead.cxx ...
Compiling src/UTaskWrite.cxx ...
Generating dictionary TasksDict.cxx ...
Compiling TasksDict.cxx ...
Creating library /home/arshad/WorkSpace/LEARN/UniGen/lib/libTasks.so ...
/usr/bin/ld: cannot find -lUniGen: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [/home/arshad/WorkSpace/LEARN/UniGen/config/Makelib:33: /home/arshad/WorkSpace/LEARN/UniGen/lib/libTasks.so] Error 1
make[1]: Leaving directory '/home/arshad/WorkSpace/LEARN/UniGen/tasks'
make: *** [Makefile:57: install] Error 2

Any help is highly appreciated
Regards
Arshad

**Comment by kresan** [comment]
Fixed in master branch with 7b6fe3cf00729ba714f987986b5675a5318983b9

Please try with new tag v2.3.1.

**Comment by arshedmasoodi** [comment]
Thanks a lot: Solved
