### ISSUE TITLE
UNIGEN=$PDW in unigenlogin.sh script

### ISSUE THREAD

**Issue by OlegGolosov** [FairRootGroup/UniGen#4]
Previously the script looked different (like the tcsh one) and produced correct path to UniGen if called from any place.
Now it only works if called from the root directory of the package.

Was this an intentional change?

**Comment by kresan** [comment]
Is fixed in develop branch with commit 71a4b147f7d8ded1a5de34fec9a3e14cecead167

Now the script can be sourced from any location
