### ISSUE TITLE
converting ampt.dat to ampt.root

### ISSUE THREAD

**Issue by arshedmasoodi** [FairRootGroup/UniGen#6]
hi,
though i am successful in converting ampt.dat to ampt.root i am getting the below error at the start ...
 
arshed@arshadmasoodi:~/WorkSpace/AMPT/data/testUniGen$ ampt2u ../stringmelting/25AGeV/ampt_25AGeV_b0to5_01/ampt.dat input.ampt ampt_test.root 10000
**Error in <TCling::RegisterModule>: cannot find dictionary module UniGenDict_rdict.pcm**
 will this affect my root files in anyway

regards 
arshad

**Comment by kresan** [comment]
The error should be fixed with cefb38a67bff55a9b206a023e350c526d8614d2a
You need to update your local version and then do `make clean_all` and `make`.
