### ISSUE TITLE
compiling unigen on ubuntu20.04 and root v6.22/06

### ISSUE THREAD

**Issue by arshedmasoodi** [FairRootGroup/UniGen#7]
i get the following error:
make
make[1]: Entering directory '/home/arshad/WorkSpace/UniGen/base'
Compiling src/URun.cxx ...
Compiling src/UPIDConverter.cxx ...
Compiling src/UEvent.cxx ...
Compiling src/UManager.cxx ...
Compiling src/UParticle.cxx ...
Compiling src/UTask.cxx ...
Generating dictionary UniGenDict.cxx ...
Warning: Unused variable rule: gROOT
Warning: Unused variable rule: gEnv
Error: Opening new rootmap file /home/arshad/WorkSpace/UniGen/lib/libUniGen.rootmap_tmp_15027
make[1]: *** [/home/arshad/WorkSpace/UniGen/config/Makelib:23: UniGenDict.cxx] Error 1
make[1]: Leaving directory '/home/arshad/WorkSpace/UniGen/base'
make[1]: Entering directory '/home/arshad/WorkSpace/UniGen/converters'
Compiling pluto2u.cpp ...
Compiling therminator2u.cpp ...
Compiling hsd2u.cpp ...
Compiling venus2u.cpp ...
Compiling ampt2u.cpp ...
Compiling evtgen2u.cpp ...
Compiling epos2u.cpp ...
Compiling hijing2u.cpp ...
Compiling urqmd2u.cpp ...
Building /home/arshad/WorkSpace/UniGen/bin/pluto2u ...
/usr/bin/ld: cannot find -lUniGen
collect2: error: ld returned 1 exit status
make[1]: *** [/home/arshad/WorkSpace/UniGen/config/Makebin:25: /home/arshad/WorkSpace/UniGen/bin/pluto2u] Error 1
make[1]: Leaving directory '/home/arshad/WorkSpace/UniGen/converters'
make[1]: Entering directory '/home/arshad/WorkSpace/UniGen/input'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/arshad/WorkSpace/UniGen/input'
make[1]: Entering directory '/home/arshad/WorkSpace/UniGen/tasks'
Compiling src/UTaskFilter.cxx ...
Compiling src/UTaskKin.cxx ...
Compiling src/UTaskWrite.cxx ...
Compiling src/UTaskGetInelastic.cxx ...
Compiling src/UTaskRead.cxx ...
Compiling src/UTaskLab2Cm.cxx ...
Compiling src/UTaskCm2Lab.cxx ...
Generating dictionary TasksDict.cxx ...
Error: Opening new rootmap file /home/arshad/WorkSpace/UniGen/lib/libTasks.rootmap_tmp_15273
make[1]: *** [/home/arshad/WorkSpace/UniGen/config/Makelib:23: TasksDict.cxx] Error 1
make[1]: Leaving directory '/home/arshad/WorkSpace/UniGen/tasks'
make: *** [Makefile:20: all] Error 2

regards
Arshad

**Comment by kresan** [comment]
Can you try the following:
```
cd /home/arshad/WorkSpace/UniGen
mkdir lib
make
```

**Comment by arshedmasoodi** [comment]
it compiles now successfully.....

thanks...

regards
Arshad

**Comment by kresan** [comment]
Is fixed in 96f14f3bc7241e122e62b23e8f968ce580a77d6c
Closing
